// Conjunto amplo de emojis estilo WhatsApp, agrupados por categoria.
// Cada item: [emoji, palavras-chave em PT/EN para busca].
// Lista compacta porém abrangente — cobre o que 99% dos usuários procuram.

export type EmojiItem = [string, string]; // [char, keywords]

export interface EmojiCategory {
  id: string;
  label: string;
  icon: string;
  items: EmojiItem[];
}

export const EMOJI_CATEGORIES: EmojiCategory[] = [
  {
    id: 'smileys',
    label: 'Carinhas e pessoas',
    icon: '😀',
    items: [
      ['😀','sorriso grin smile feliz happy'],
      ['😃','sorriso grin smile feliz happy'],
      ['😄','sorriso grin smile feliz happy'],
      ['😁','sorriso grin smile feliz happy'],
      ['😆','riso laugh feliz happy'],
      ['😅','riso suor laugh sweat'],
      ['🤣','rolando rofl rolling laugh'],
      ['😂','chorando rindo joy laugh tears'],
      ['🙂','sorriso slight smile'],
      ['🙃','invertido upside down'],
      ['😉','piscada wink'],
      ['😊','sorriso blush feliz happy'],
      ['😇','anjo angel halo'],
      ['🥰','amor amor love hearts'],
      ['😍','apaixonado heart eyes love'],
      ['🤩','estrela star struck'],
      ['😘','beijo kiss'],
      ['😗','beijo kiss'],
      ['😚','beijo kiss'],
      ['😙','beijo kiss'],
      ['🥲','sorriso lagrima smiling tear'],
      ['😋','delicioso yum tasty'],
      ['😛','lingua tongue'],
      ['😜','piscada lingua wink tongue'],
      ['🤪','louco zany crazy'],
      ['😝','lingua tongue'],
      ['🤑','dinheiro money mouth'],
      ['🤗','abraço hug hugging'],
      ['🤭','tampando boca hand mouth'],
      ['🤫','silencio shh quiet'],
      ['🤔','pensando thinking'],
      ['🤐','zipped boca zip'],
      ['🤨','sobrancelha levantada raised eyebrow'],
      ['😐','neutro neutral'],
      ['😑','sem expressao expressionless'],
      ['😶','sem boca no mouth'],
      ['😶‍🌫️','nuvem fog face'],
      ['😏','malicioso smirk'],
      ['😒','nao impressionado unamused'],
      ['🙄','olhos revirados eye roll'],
      ['😬','careta grimace'],
      ['😮‍💨','suspiro exhale'],
      ['🤥','mentiroso lying liar'],
      ['😌','aliviado relieved'],
      ['😔','pensativo pensive triste sad'],
      ['😪','sonolento sleepy'],
      ['🤤','baba drool'],
      ['😴','dormindo sleep'],
      ['😷','mascara mask'],
      ['🤒','febre thermometer sick doente'],
      ['🤕','machucado bandage hurt'],
      ['🤢','enjoado nausea'],
      ['🤮','vomito vomit'],
      ['🤧','espirro sneeze'],
      ['🥵','calor hot sweat'],
      ['🥶','frio cold freezing'],
      ['🥴','tonto woozy'],
      ['😵','tonto dizzy'],
      ['😵‍💫','espiral spiral'],
      ['🤯','explodindo mind blown'],
      ['🤠','cowboy chapeu'],
      ['🥳','festa party'],
      ['🥸','disfarce disguise'],
      ['😎','oculos cool sunglasses'],
      ['🤓','nerd'],
      ['🧐','monocle monoculo'],
      ['😕','confuso confused'],
      ['😟','preocupado worried'],
      ['🙁','triste frowning'],
      ['☹️','triste frown'],
      ['😮','boca aberta open mouth'],
      ['😯','calado hushed'],
      ['😲','impressionado astonished'],
      ['😳','vermelho flushed'],
      ['🥺','suplicando pleading'],
      ['😦','medo frown'],
      ['😧','angustia anguished'],
      ['😨','assustado fearful'],
      ['😰','suor frio anxious'],
      ['😥','triste sad relief'],
      ['😢','chorando cry'],
      ['😭','chorando muito loud cry'],
      ['😱','grito scream'],
      ['😖','aflito confounded'],
      ['😣','perseverando persevere'],
      ['😞','decepcionado disappointed'],
      ['😓','suor downcast sweat'],
      ['😩','cansado weary'],
      ['😫','exausto tired'],
      ['🥱','bocejo yawn'],
      ['😤','triunfante huff'],
      ['😡','bravo angry rage furioso'],
      ['😠','bravo angry'],
      ['🤬','xingando cursing'],
      ['😈','diabo devil'],
      ['👿','diabo bravo angry devil'],
      ['💀','caveira skull morto'],
      ['☠️','caveira skull'],
      ['💩','coco poop'],
      ['🤡','palhaco clown'],
      ['👹','ogro ogre'],
      ['👺','goblin'],
      ['👻','fantasma ghost'],
      ['👽','alien'],
      ['👾','monstro alien'],
      ['🤖','robo robot'],
      ['😺','gato cat smile'],
      ['😸','gato cat grin'],
      ['😹','gato cat joy'],
      ['😻','gato cat hearts'],
      ['😼','gato cat smirk'],
      ['😽','gato cat kiss'],
      ['🙀','gato cat scared'],
      ['😿','gato cat cry'],
      ['😾','gato cat angry'],
    ],
  },
  {
    id: 'gestures',
    label: 'Gestos e corpo',
    icon: '👋',
    items: [
      ['👋','aceno wave ola hi'],
      ['🤚','mao raised hand'],
      ['🖐️','mao spread hand'],
      ['✋','mao stop'],
      ['🖖','vulcano spock'],
      ['👌','ok'],
      ['🤌','italiano pinched'],
      ['🤏','pinca pinch'],
      ['✌️','paz peace victoria victory'],
      ['🤞','dedos cruzados crossed fingers'],
      ['🫰','dedo coracao finger heart'],
      ['🤟','love rock'],
      ['🤘','rock horns'],
      ['🤙','call shaka me liga'],
      ['👈','aponta esquerda left'],
      ['👉','aponta direita right'],
      ['👆','aponta cima up'],
      ['🖕','dedo medio middle'],
      ['👇','aponta baixo down'],
      ['☝️','dedo apontado index'],
      ['👍','joinha thumbs up like'],
      ['👎','negativo thumbs down dislike'],
      ['✊','soco fist'],
      ['👊','soco punch'],
      ['🤛','esquerda left fist'],
      ['🤜','direita right fist'],
      ['👏','palmas clap'],
      ['🙌','maos para cima raised hands'],
      ['👐','maos abertas open hands'],
      ['🤲','maos juntas palms'],
      ['🤝','aperto handshake deal'],
      ['🙏','obrigado prayer thanks please'],
      ['✍️','escrevendo writing'],
      ['💅','unhas nail'],
      ['🤳','selfie'],
      ['💪','musculo muscle forte strong'],
      ['🦾','protese mecanica mechanical arm'],
      ['🦵','perna leg'],
      ['🦶','pe foot'],
      ['👂','orelha ear'],
      ['🦻','orelha aparelho hearing'],
      ['👃','nariz nose'],
      ['🧠','cerebro brain'],
      ['🦷','dente tooth'],
      ['🦴','osso bone'],
      ['👀','olhos eyes'],
      ['👁️','olho eye'],
      ['👅','lingua tongue'],
      ['👄','boca mouth lips'],
      ['💋','beijo kiss'],
      ['👶','bebe baby'],
      ['🧒','crianca child'],
      ['👦','menino boy'],
      ['👧','menina girl'],
      ['🧑','pessoa person'],
      ['👨','homem man'],
      ['👩','mulher woman'],
      ['🧓','idoso elder'],
      ['👴','vovo grandpa'],
      ['👵','vovo grandma'],
      ['👮','policial police'],
      ['🕵️','detetive detective spy'],
      ['💂','guarda guard'],
      ['👷','trabalhador construction worker'],
      ['🤴','principe prince'],
      ['👸','princesa princess'],
      ['🥷','ninja'],
      ['👰','noiva bride'],
      ['🤵','noivo groom'],
      ['🤰','gravida pregnant'],
      ['🤱','amamentando breastfeeding'],
      ['👼','anjo bebe baby angel'],
      ['🎅','papai noel santa'],
      ['🤶','mamae noel mrs santa'],
      ['🦸','heroi hero'],
      ['🦹','vilao villain'],
      ['🧙','mago wizard'],
      ['🧚','fada fairy'],
      ['🧛','vampiro vampire'],
      ['🧜','sereia mermaid'],
      ['🧝','elfo elf'],
      ['🧞','genio genie'],
      ['🧟','zumbi zombie'],
      ['💆','massagem massage'],
      ['💇','cabelo haircut'],
      ['🚶','caminhando walking'],
      ['🧍','de pe standing'],
      ['🧎','ajoelhado kneeling'],
      ['🏃','correndo running'],
      ['💃','dancando dancing'],
      ['🕺','dancando dancing man'],
      ['👯','dancando dancers'],
      ['🧖','sauna'],
      ['🧗','escalando climbing'],
      ['🤺','esgrima fencing'],
      ['🏇','jockey'],
      ['⛷️','ski'],
      ['🏂','snowboard'],
      ['🏌️','golfe golf'],
      ['🏄','surf'],
      ['🚣','remo rowing'],
      ['🏊','natacao swimming'],
      ['⛹️','basquete basketball'],
      ['🏋️','levantando peso lifting'],
      ['🚴','ciclismo bike cycling'],
      ['🚵','mountain bike'],
      ['🤸','acrobacia cartwheel'],
      ['🤼','luta wrestling'],
      ['🤽','polo aquatico water polo'],
      ['🤾','handball'],
      ['🤹','malabarista juggling'],
      ['🧘','yoga meditando'],
      ['🛀','banho bath'],
      ['🛌','na cama bed'],
      ['👫','casal couple'],
      ['👭','duas mulheres women'],
      ['👬','dois homens men'],
      ['💑','casal coracao couple heart'],
      ['💏','casal beijo couple kiss'],
      ['👪','familia family'],
    ],
  },
  {
    id: 'animals',
    label: 'Animais e natureza',
    icon: '🐶',
    items: [
      ['🐶','cachorro dog'],
      ['🐱','gato cat'],
      ['🐭','rato mouse'],
      ['🐹','hamster'],
      ['🐰','coelho rabbit bunny'],
      ['🦊','raposa fox'],
      ['🐻','urso bear'],
      ['🐼','panda'],
      ['🐻‍❄️','urso polar polar bear'],
      ['🐨','koala'],
      ['🐯','tigre tiger'],
      ['🦁','leao lion'],
      ['🐮','vaca cow'],
      ['🐷','porco pig'],
      ['🐽','focinho pig nose'],
      ['🐸','sapo frog'],
      ['🐵','macaco monkey'],
      ['🙈','macaco monkey see'],
      ['🙉','macaco monkey hear'],
      ['🙊','macaco monkey speak'],
      ['🐒','macaco monkey'],
      ['🐔','galinha chicken'],
      ['🐧','pinguim penguin'],
      ['🐦','passaro bird'],
      ['🐤','pintinho chick'],
      ['🐣','pintinho hatching chick'],
      ['🐥','pintinho front chick'],
      ['🦆','pato duck'],
      ['🦅','aguia eagle'],
      ['🦉','coruja owl'],
      ['🦇','morcego bat'],
      ['🐺','lobo wolf'],
      ['🐗','javali boar'],
      ['🐴','cavalo horse'],
      ['🦄','unicornio unicorn'],
      ['🐝','abelha bee'],
      ['🪱','minhoca worm'],
      ['🐛','lagarta caterpillar'],
      ['🦋','borboleta butterfly'],
      ['🐌','caracol snail'],
      ['🐞','joaninha ladybug'],
      ['🐜','formiga ant'],
      ['🪰','mosca fly'],
      ['🪲','besouro beetle'],
      ['🦗','grilo cricket'],
      ['🕷️','aranha spider'],
      ['🦂','escorpiao scorpion'],
      ['🐢','tartaruga turtle'],
      ['🐍','cobra snake'],
      ['🦎','lagarto lizard'],
      ['🦖','t rex dinossauro'],
      ['🦕','dinossauro brontosaurus'],
      ['🐙','polvo octopus'],
      ['🦑','lula squid'],
      ['🦐','camarao shrimp'],
      ['🦞','lagosta lobster'],
      ['🦀','caranguejo crab'],
      ['🐡','baiacu pufferfish'],
      ['🐠','peixe tropical fish'],
      ['🐟','peixe fish'],
      ['🐬','golfinho dolphin'],
      ['🐳','baleia whale'],
      ['🦈','tubarao shark'],
      ['🐊','crocodilo crocodile'],
      ['🐅','tigre tiger'],
      ['🐆','leopardo leopard'],
      ['🦓','zebra'],
      ['🦍','gorila gorilla'],
      ['🦧','orangotango orangutan'],
      ['🐘','elefante elephant'],
      ['🦏','rinoceronte rhino'],
      ['🦛','hipopotamo hippo'],
      ['🐪','camelo camel'],
      ['🐫','camelo camel'],
      ['🦒','girafa giraffe'],
      ['🦘','canguru kangaroo'],
      ['🐃','bufalo buffalo'],
      ['🐂','boi ox'],
      ['🐄','vaca cow'],
      ['🐎','cavalo horse'],
      ['🐖','porco pig'],
      ['🐏','carneiro ram'],
      ['🐑','ovelha sheep'],
      ['🦙','lhama llama'],
      ['🐐','cabra goat'],
      ['🦌','veado deer'],
      ['🐕','cachorro dog'],
      ['🐩','poodle'],
      ['🦮','cao guia guide dog'],
      ['🐕‍🦺','cao servico service dog'],
      ['🐈','gato cat'],
      ['🐈‍⬛','gato preto black cat'],
      ['🐓','galo rooster'],
      ['🦃','peru turkey'],
      ['🦤','dodo'],
      ['🦚','pavao peacock'],
      ['🦜','papagaio parrot'],
      ['🦢','cisne swan'],
      ['🦩','flamingo'],
      ['🌵','cacto cactus'],
      ['🎄','arvore natal christmas tree'],
      ['🌲','pinheiro evergreen'],
      ['🌳','arvore tree'],
      ['🌴','palmeira palm'],
      ['🪴','vaso plant'],
      ['🌱','muda seedling'],
      ['🌿','folha herb'],
      ['☘️','trevo shamrock'],
      ['🍀','trevo clover sorte luck'],
      ['🎋','tanabata bamboo'],
      ['🎍','pinheiro pine'],
      ['🍃','folhas leaves'],
      ['🍂','folhas outono fall leaves'],
      ['🍁','folha bordo maple'],
      ['🌾','arroz rice plant'],
      ['🌷','tulipa tulip'],
      ['🌹','rosa rose'],
      ['🥀','flor murcha wilted'],
      ['🌺','hibisco hibiscus'],
      ['🌸','flor sakura blossom'],
      ['🌼','flor blossom'],
      ['🌻','girassol sunflower'],
      ['🌞','sol sun rosto face'],
      ['🌝','lua face moon'],
      ['🌛','lua moon'],
      ['🌜','lua moon'],
      ['🌚','lua nova new moon'],
      ['🌕','lua cheia full moon'],
      ['🌖','lua minguante waning'],
      ['🌗','lua quarto last quarter'],
      ['🌘','lua minguante crescent'],
      ['🌑','lua nova new moon'],
      ['🌒','lua crescente waxing'],
      ['🌓','lua quarto first quarter'],
      ['🌔','lua gibosa waxing gibbous'],
      ['🌙','lua crescent moon'],
      ['🌎','terra americas earth'],
      ['🌍','terra africa earth'],
      ['🌏','terra asia earth'],
      ['🪐','planeta saturno saturn'],
      ['💫','tontura dizzy'],
      ['⭐','estrela star'],
      ['🌟','estrela glowing'],
      ['✨','brilho sparkles'],
      ['☄️','cometa comet'],
      ['☀️','sol sun'],
      ['🌤️','sol nuvem sun cloud'],
      ['⛅','nuvem cloud'],
      ['🌥️','nublado cloudy'],
      ['☁️','nuvem cloud'],
      ['🌦️','sol chuva sun rain'],
      ['🌧️','chuva rain'],
      ['⛈️','tempestade storm'],
      ['🌩️','raio lightning'],
      ['🌨️','neve snow'],
      ['❄️','floco snowflake'],
      ['☃️','boneco neve snowman'],
      ['⛄','boneco neve snowman'],
      ['🌬️','vento wind'],
      ['💨','vento dash'],
      ['🌪️','tornado'],
      ['🌫️','neblina fog'],
      ['🌊','onda wave'],
      ['💧','gota droplet'],
      ['💦','suor sweat drops'],
      ['☔','guarda chuva umbrella'],
      ['🌈','arco iris rainbow'],
      ['🔥','fogo fire'],
    ],
  },
  {
    id: 'food',
    label: 'Comida e bebida',
    icon: '🍔',
    items: [
      ['🍏','maca verde green apple'],
      ['🍎','maca apple'],
      ['🍐','pera pear'],
      ['🍊','laranja orange'],
      ['🍋','limao lemon'],
      ['🍌','banana'],
      ['🍉','melancia watermelon'],
      ['🍇','uva grape'],
      ['🍓','morango strawberry'],
      ['🫐','blueberry'],
      ['🍈','melao melon'],
      ['🍒','cereja cherry'],
      ['🍑','pessego peach'],
      ['🥭','manga mango'],
      ['🍍','abacaxi pineapple'],
      ['🥥','coco coconut'],
      ['🥝','kiwi'],
      ['🍅','tomate tomato'],
      ['🍆','berinjela eggplant'],
      ['🥑','abacate avocado'],
      ['🥦','brocolis broccoli'],
      ['🥬','folha greens'],
      ['🥒','pepino cucumber'],
      ['🌶️','pimenta pepper'],
      ['🫑','pimentao bell pepper'],
      ['🌽','milho corn'],
      ['🥕','cenoura carrot'],
      ['🫒','azeitona olive'],
      ['🧄','alho garlic'],
      ['🧅','cebola onion'],
      ['🥔','batata potato'],
      ['🍠','batata doce sweet potato'],
      ['🥐','croissant'],
      ['🥯','bagel'],
      ['🍞','pao bread'],
      ['🥖','baguete baguette'],
      ['🧀','queijo cheese'],
      ['🥚','ovo egg'],
      ['🍳','ovo frito egg'],
      ['🧈','manteiga butter'],
      ['🥞','panqueca pancake'],
      ['🧇','waffle'],
      ['🥓','bacon'],
      ['🥩','carne steak'],
      ['🍗','perna chicken leg'],
      ['🍖','carne meat'],
      ['🌭','cachorro quente hot dog'],
      ['🍔','hamburguer burger'],
      ['🍟','batata frita fries'],
      ['🍕','pizza'],
      ['🥪','sanduiche sandwich'],
      ['🥙','wrap'],
      ['🧆','falafel'],
      ['🌮','taco'],
      ['🌯','burrito'],
      ['🥗','salada salad'],
      ['🥘','panela paella'],
      ['🫕','fondue'],
      ['🍝','espaguete pasta'],
      ['🍜','ramen lamen'],
      ['🍲','sopa stew soup'],
      ['🍛','curry'],
      ['🍣','sushi'],
      ['🍱','bento'],
      ['🥟','dumpling'],
      ['🦪','ostra oyster'],
      ['🍤','tempura camarao shrimp'],
      ['🍙','onigiri'],
      ['🍚','arroz rice'],
      ['🍘','rice cracker'],
      ['🍥','fish cake'],
      ['🥠','fortune cookie'],
      ['🥮','mooncake'],
      ['🍢','oden'],
      ['🍡','dango'],
      ['🍧','raspadinha shaved ice'],
      ['🍨','sorvete ice cream'],
      ['🍦','sorvete soft ice cream'],
      ['🥧','torta pie'],
      ['🧁','cupcake'],
      ['🍰','bolo cake'],
      ['🎂','bolo aniversario birthday cake'],
      ['🍮','pudim flan'],
      ['🍭','pirulito lollipop'],
      ['🍬','bala candy'],
      ['🍫','chocolate'],
      ['🍿','pipoca popcorn'],
      ['🍩','rosquinha donut'],
      ['🍪','biscoito cookie'],
      ['🌰','castanha chestnut'],
      ['🥜','amendoim peanut'],
      ['🍯','mel honey'],
      ['🥛','leite milk'],
      ['🍼','mamadeira bottle'],
      ['☕','cafe coffee'],
      ['🍵','cha tea'],
      ['🧃','suco juice'],
      ['🥤','refri soft drink'],
      ['🧋','bubble tea boba'],
      ['🍶','sake'],
      ['🍺','cerveja beer'],
      ['🍻','cervejas beers'],
      ['🥂','tiim brinde toast'],
      ['🍷','vinho wine'],
      ['🥃','whisky'],
      ['🍸','martini cocktail'],
      ['🍹','tropical drink'],
      ['🧉','mate'],
      ['🍾','champanhe champagne'],
      ['🧊','gelo ice'],
      ['🥄','colher spoon'],
      ['🍴','garfo faca fork knife'],
      ['🍽️','prato plate'],
      ['🥣','tigela bowl'],
      ['🥡','take out'],
      ['🥢','hashi chopsticks'],
    ],
  },
  {
    id: 'activities',
    label: 'Atividades e esportes',
    icon: '⚽',
    items: [
      ['⚽','futebol soccer'],
      ['🏀','basquete basketball'],
      ['🏈','futebol americano football'],
      ['⚾','beisebol baseball'],
      ['🥎','softball'],
      ['🎾','tenis tennis'],
      ['🏐','volei volleyball'],
      ['🏉','rugby'],
      ['🥏','frisbee'],
      ['🎱','sinuca billiards'],
      ['🪀','io io yoyo'],
      ['🏓','tenis mesa ping pong'],
      ['🏸','badminton'],
      ['🏒','hockey'],
      ['🏑','field hockey'],
      ['🥍','lacrosse'],
      ['🏏','cricket'],
      ['🪃','bumerangue boomerang'],
      ['🥅','gol goal net'],
      ['⛳','golfe golf flag'],
      ['🪁','pipa kite'],
      ['🏹','arco bow arrow'],
      ['🎣','pesca fishing'],
      ['🤿','mergulho diving'],
      ['🥊','boxe boxing'],
      ['🥋','karate judo'],
      ['🎽','camisa corrida running shirt'],
      ['🛹','skate'],
      ['🛼','patins roller skate'],
      ['🛷','sled'],
      ['⛸️','patinacao ice skate'],
      ['🥌','curling'],
      ['🎿','ski'],
      ['⛷️','esquiando skier'],
      ['🏂','snowboard'],
      ['🪂','paraquedas parachute'],
      ['🏋️','musculacao weight lifting'],
      ['🤺','esgrima fencing'],
      ['🤼','luta wrestling'],
      ['🤸','ginastica gymnastics'],
      ['⛹️','dribling basketball'],
      ['🤾','handball'],
      ['🏌️','golfe golf'],
      ['🏇','jockey corrida cavalos'],
      ['🧘','yoga meditacao'],
      ['🏄','surfista surf'],
      ['🏊','natacao swim'],
      ['🤽','polo aquatico water polo'],
      ['🚣','remo rowing'],
      ['🧗','escalada climbing'],
      ['🚵','mountain bike'],
      ['🚴','ciclismo bike'],
      ['🏆','trofeu trophy'],
      ['🥇','ouro gold medal'],
      ['🥈','prata silver medal'],
      ['🥉','bronze medal'],
      ['🏅','medalha medal'],
      ['🎖️','medalha militar military'],
      ['🏵️','rosette'],
      ['🎗️','laco ribbon'],
      ['🎫','ingresso ticket'],
      ['🎟️','ingresso admission'],
      ['🎪','circo circus'],
      ['🤹','malabarista juggle'],
      ['🎭','teatro mascara theater'],
      ['🩰','sapatilha ballet'],
      ['🎨','arte palette artist'],
      ['🎬','clapper filme movie'],
      ['🎤','microfone mic'],
      ['🎧','fone headphone'],
      ['🎼','partitura music'],
      ['🎹','piano'],
      ['🥁','bateria drum'],
      ['🪘','tambor drum'],
      ['🎷','sax sax'],
      ['🎺','trompete trumpet'],
      ['🎸','guitarra guitar'],
      ['🪕','banjo'],
      ['🎻','violino violin'],
      ['🎲','dado dice'],
      ['♟️','xadrez chess'],
      ['🎯','alvo dart target'],
      ['🎳','boliche bowling'],
      ['🎮','videogame controle'],
      ['🕹️','joystick'],
      ['🎰','caca niqueis slot machine'],
      ['🧩','quebra cabeca puzzle'],
    ],
  },
  {
    id: 'travel',
    label: 'Viagens e lugares',
    icon: '🚗',
    items: [
      ['🚗','carro car'],
      ['🚕','taxi'],
      ['🚙','suv'],
      ['🚌','onibus bus'],
      ['🚎','trolebus trolley'],
      ['🏎️','carro corrida race car'],
      ['🚓','viatura police car'],
      ['🚑','ambulancia ambulance'],
      ['🚒','bombeiros fire truck'],
      ['🚐','van minibus'],
      ['🛻','picape pickup'],
      ['🚚','caminhao truck'],
      ['🚛','caminhao articulado lorry'],
      ['🚜','trator tractor'],
      ['🦯','bengala white cane'],
      ['🦽','cadeira rodas wheelchair'],
      ['🦼','cadeira motor wheelchair'],
      ['🛴','patinete scooter'],
      ['🚲','bicicleta bike'],
      ['🛵','moto scooter'],
      ['🏍️','motocicleta motorcycle'],
      ['🛺','tuk tuk'],
      ['🚨','sirene siren police'],
      ['🚔','viatura police'],
      ['🚍','onibus oncoming bus'],
      ['🚘','carro oncoming car'],
      ['🚖','taxi oncoming'],
      ['🚡','teleferico aerial tramway'],
      ['🚠','teleferico mountain cable'],
      ['🚟','suspended railway'],
      ['🚃','vagao tram'],
      ['🚋','bonde tram car'],
      ['🚞','trem montanha mountain railway'],
      ['🚝','monotrilho monorail'],
      ['🚄','trem alta velocidade speed train'],
      ['🚅','bullet train'],
      ['🚈','trem light rail'],
      ['🚂','locomotiva locomotive'],
      ['🚆','trem train'],
      ['🚇','metro metro'],
      ['🚊','tram bonde'],
      ['🚉','estacao station'],
      ['✈️','aviao plane'],
      ['🛫','decolagem departure'],
      ['🛬','pouso arrival'],
      ['🛩️','aviao pequeno small plane'],
      ['🪂','paraquedas parachute'],
      ['💺','assento seat'],
      ['🚀','foguete rocket'],
      ['🛸','disco voador ufo'],
      ['🚁','helicoptero helicopter'],
      ['🛶','canoa canoe'],
      ['⛵','veleiro sailboat'],
      ['🚤','lancha speedboat'],
      ['🛥️','iate motor boat'],
      ['🛳️','cruzeiro cruise'],
      ['⛴️','balsa ferry'],
      ['🚢','navio ship'],
      ['⚓','ancora anchor'],
      ['⛽','gasolina fuel'],
      ['🚧','obras construction'],
      ['🚦','semaforo traffic light'],
      ['🚥','semaforo horizontal traffic'],
      ['🗺️','mapa map'],
      ['🗿','moai estatua'],
      ['🗽','estatua liberdade liberty'],
      ['🗼','torre toquio tokyo tower'],
      ['🏰','castelo castle'],
      ['🏯','castelo japones castle'],
      ['🏟️','estadio stadium'],
      ['🎡','roda gigante ferris wheel'],
      ['🎢','montanha russa coaster'],
      ['🎠','carrossel carousel'],
      ['⛲','fonte fountain'],
      ['⛱️','sombrinha umbrella beach'],
      ['🏖️','praia beach'],
      ['🏝️','ilha island'],
      ['🏜️','deserto desert'],
      ['🌋','vulcao volcano'],
      ['⛰️','montanha mountain'],
      ['🏔️','montanha neve snow mountain'],
      ['🗻','fuji'],
      ['🏕️','camping'],
      ['⛺','barraca tent'],
      ['🏠','casa house'],
      ['🏡','casa jardim house garden'],
      ['🏘️','casas houses'],
      ['🏚️','casa abandonada derelict'],
      ['🏗️','construcao construction'],
      ['🏭','fabrica factory'],
      ['🏢','escritorio office'],
      ['🏬','loja shopping'],
      ['🏣','correio posto'],
      ['🏤','correio europeu post office'],
      ['🏥','hospital'],
      ['🏦','banco bank'],
      ['🏨','hotel'],
      ['🏪','conveniencia convenience store'],
      ['🏫','escola school'],
      ['🏩','love hotel'],
      ['💒','casamento wedding'],
      ['🏛️','classico classical'],
      ['⛪','igreja church'],
      ['🕌','mesquita mosque'],
      ['🛕','templo hindu temple'],
      ['🕍','sinagoga synagogue'],
      ['⛩️','torii santuario shrine'],
      ['🕋','kaaba'],
      ['🌃','cidade noite night city'],
      ['🌆','por do sol sunset'],
      ['🌇','sunrise'],
      ['🌉','ponte bridge night'],
      ['🌅','amanhecer sunrise'],
      ['🌄','sol nasce mountain'],
      ['🏞️','parque national park'],
      ['🌌','via lactea milky way'],
    ],
  },
  {
    id: 'objects',
    label: 'Objetos',
    icon: '💡',
    items: [
      ['⌚','relogio watch'],
      ['📱','celular phone iphone'],
      ['📲','celular seta phone'],
      ['💻','laptop notebook'],
      ['⌨️','teclado keyboard'],
      ['🖥️','desktop computer'],
      ['🖨️','impressora printer'],
      ['🖱️','mouse'],
      ['🖲️','trackball'],
      ['🕹️','joystick'],
      ['🗜️','torno clamp'],
      ['💽','minidisc'],
      ['💾','disquete floppy'],
      ['💿','cd'],
      ['📀','dvd'],
      ['📼','vhs'],
      ['📷','camera'],
      ['📸','camera flash'],
      ['📹','filmadora video camera'],
      ['🎥','filmagem movie camera'],
      ['📽️','projetor projector'],
      ['🎞️','filme film frames'],
      ['📞','telefone phone'],
      ['☎️','telefone fixo phone'],
      ['📟','pager'],
      ['📠','fax'],
      ['📺','tv television'],
      ['📻','radio'],
      ['🎙️','microfone studio mic'],
      ['🎚️','volume slider'],
      ['🎛️','controle knobs'],
      ['🧭','bussola compass'],
      ['⏱️','cronometro stopwatch'],
      ['⏲️','timer'],
      ['⏰','despertador alarm'],
      ['🕰️','relogio mantelpiece'],
      ['⌛','ampulheta hourglass'],
      ['⏳','ampulheta hourglass'],
      ['📡','antena satellite'],
      ['🔋','bateria battery'],
      ['🔌','tomada plug'],
      ['💡','lampada bulb idea'],
      ['🔦','lanterna flashlight'],
      ['🕯️','vela candle'],
      ['🪔','lamparina diya'],
      ['🧯','extintor fire extinguisher'],
      ['🛢️','barril oil drum'],
      ['💸','dinheiro voando money wings'],
      ['💵','dolar dollar'],
      ['💴','iene yen'],
      ['💶','euro'],
      ['💷','libra pound'],
      ['🪙','moeda coin'],
      ['💰','dinheiro saco money bag'],
      ['💳','cartao credit card'],
      ['💎','diamante gem'],
      ['⚖️','balanca scale'],
      ['🪜','escada ladder'],
      ['🧰','caixa ferramentas toolbox'],
      ['🔧','chave inglesa wrench'],
      ['🔨','martelo hammer'],
      ['⚒️','martelo picareta hammer pick'],
      ['🛠️','ferramentas tools'],
      ['⛏️','picareta pick'],
      ['🪛','chave fenda screwdriver'],
      ['🔩','parafuso screw'],
      ['⚙️','engrenagem gear'],
      ['🪤','ratoeira mouse trap'],
      ['🧱','tijolo brick'],
      ['⛓️','corrente chains'],
      ['🧲','ima magnet'],
      ['🔫','arma gun water'],
      ['💣','bomba'],
      ['🧨','dinamite firecracker'],
      ['🪓','machado axe'],
      ['🔪','faca knife'],
      ['🗡️','adaga dagger'],
      ['⚔️','espadas swords'],
      ['🛡️','escudo shield'],
      ['🚬','cigarro cigarette'],
      ['⚰️','caixao coffin'],
      ['🪦','tumulo headstone'],
      ['⚱️','urna funeral urn'],
      ['🏺','anfora amphora'],
      ['🔮','bola cristal crystal ball'],
      ['📿','japamala beads'],
      ['🧿','olho turco nazar'],
      ['💈','barbeiro barber pole'],
      ['🔭','telescopio telescope'],
      ['🔬','microscopio microscope'],
      ['🕳️','buraco hole'],
      ['🩹','curativo bandage'],
      ['🩺','estetoscopio stethoscope'],
      ['💊','remedio pill'],
      ['💉','seringa syringe'],
      ['🩸','sangue blood'],
      ['🧬','dna'],
      ['🦠','virus microbe'],
      ['🧫','placa petri dish'],
      ['🧪','tubo ensaio test tube'],
      ['🌡️','termometro thermometer'],
      ['🧹','vassoura broom'],
      ['🧺','cesta basket'],
      ['🧻','papel higienico toilet paper'],
      ['🚽','vaso sanitario toilet'],
      ['🚰','agua potable water'],
      ['🚿','chuveiro shower'],
      ['🛁','banheira bath'],
      ['🧼','sabao soap'],
      ['🪥','escova dente toothbrush'],
      ['🪒','navalha razor'],
      ['🧽','esponja sponge'],
      ['🪣','balde bucket'],
      ['🧴','frasco lotion'],
      ['🛎️','sininho bell'],
      ['🔑','chave key'],
      ['🗝️','chave antiga old key'],
      ['🚪','porta door'],
      ['🪑','cadeira chair'],
      ['🛋️','sofa couch'],
      ['🛏️','cama bed'],
      ['🛌','dormindo cama bed'],
      ['🧸','ursinho teddy bear'],
      ['🖼️','quadro picture frame'],
      ['🪞','espelho mirror'],
      ['🪟','janela window'],
      ['🛍️','sacolas shopping bags'],
      ['🛒','carrinho cart'],
      ['🎁','presente gift'],
      ['🎈','balao balloon'],
      ['🎏','carpa koinobori'],
      ['🎀','laco ribbon bow'],
      ['🎊','confete confetti'],
      ['🎉','festa party'],
      ['🎎','bonecas dolls'],
      ['🏮','lanterna lantern'],
      ['🪅','pinata'],
      ['🪆','matrioska doll'],
      ['✉️','envelope email'],
      ['📩','envelope flecha'],
      ['📨','envelope incoming'],
      ['📧','email mail'],
      ['💌','carta amor love letter'],
      ['📥','inbox tray'],
      ['📤','outbox tray'],
      ['📦','caixa box pacote'],
      ['🏷️','etiqueta label tag'],
      ['📪','caixa correio mailbox'],
      ['📫','caixa correio mailbox'],
      ['📬','caixa correio mailbox'],
      ['📭','caixa correio mailbox'],
      ['📮','caixa postal postbox'],
      ['📜','pergaminho scroll'],
      ['📃','pagina page'],
      ['📄','documento document'],
      ['📑','marcador bookmark tabs'],
      ['🧾','recibo receipt'],
      ['📊','grafico bar chart'],
      ['📈','grafico subindo chart up'],
      ['📉','grafico descendo chart down'],
      ['🗒️','bloco notes spiral'],
      ['🗓️','agenda calendar spiral'],
      ['📆','calendario calendar'],
      ['📅','calendario calendar'],
      ['🗑️','lixeira trash'],
      ['📇','indice card index'],
      ['🗃️','arquivo file box'],
      ['🗳️','urna ballot box'],
      ['🗄️','arquivo cabinet'],
      ['📋','prancheta clipboard'],
      ['📁','pasta folder'],
      ['📂','pasta aberta open folder'],
      ['🗂️','divider'],
      ['🗞️','jornal newspaper'],
      ['📰','jornal newspaper'],
      ['📓','caderno notebook'],
      ['📔','caderno decorado notebook'],
      ['📒','livro contabil ledger'],
      ['📕','livro fechado closed book'],
      ['📗','livro verde green book'],
      ['📘','livro azul blue book'],
      ['📙','livro laranja orange book'],
      ['📚','livros books'],
      ['📖','livro aberto open book'],
      ['🔖','marcador bookmark'],
      ['🧷','alfinete safety pin'],
      ['🔗','link chain'],
      ['📎','clipe paper clip'],
      ['🖇️','clipes paper clips'],
      ['📐','esquadro triangular ruler'],
      ['📏','regua ruler'],
      ['📌','tachinha pushpin'],
      ['📍','marcador round pushpin'],
      ['✂️','tesoura scissors'],
      ['🖊️','caneta pen'],
      ['🖋️','caneta tinteiro fountain pen'],
      ['✒️','caneta nib'],
      ['🖌️','pincel paintbrush'],
      ['🖍️','giz crayon'],
      ['📝','escrever memo writing'],
      ['✏️','lapis pencil'],
      ['🔍','lupa magnifying'],
      ['🔎','lupa magnifying'],
      ['🔏','cadeado caneta lock pen'],
      ['🔐','cadeado chave lock key'],
      ['🔒','cadeado lock'],
      ['🔓','cadeado aberto unlock'],
    ],
  },
  {
    id: 'symbols',
    label: 'Símbolos',
    icon: '❤️',
    items: [
      ['❤️','coracao vermelho red heart'],
      ['🧡','coracao laranja orange heart'],
      ['💛','coracao amarelo yellow heart'],
      ['💚','coracao verde green heart'],
      ['💙','coracao azul blue heart'],
      ['💜','coracao roxo purple heart'],
      ['🖤','coracao preto black heart'],
      ['🤍','coracao branco white heart'],
      ['🤎','coracao marrom brown heart'],
      ['💔','coracao partido broken heart'],
      ['❣️','coracao exclamacao heart'],
      ['💕','dois coracoes two hearts'],
      ['💞','coracoes girando hearts'],
      ['💓','coracao batendo beating heart'],
      ['💗','coracao crescendo growing heart'],
      ['💖','coracao brilhante sparkling'],
      ['💘','flecha cupido cupid'],
      ['💝','coracao laco heart ribbon'],
      ['💟','heart decoration'],
      ['☮️','paz peace'],
      ['✝️','cruz cross'],
      ['☪️','crescente estrela islam'],
      ['🕉️','om hindu'],
      ['☸️','dharma wheel'],
      ['✡️','estrela davi star david'],
      ['🔯','hexagrama hexagram'],
      ['🕎','menora menorah'],
      ['☯️','yin yang'],
      ['☦️','cruz ortodoxa orthodox cross'],
      ['🛐','local culto worship'],
      ['⛎','ofiuco ophiuchus'],
      ['♈','aries'],
      ['♉','touro taurus'],
      ['♊','gemeos gemini'],
      ['♋','cancer'],
      ['♌','leao leo'],
      ['♍','virgem virgo'],
      ['♎','libra'],
      ['♏','escorpiao scorpio'],
      ['♐','sagitario sagittarius'],
      ['♑','capricornio capricorn'],
      ['♒','aquario aquarius'],
      ['♓','peixes pisces'],
      ['🆔','id'],
      ['⚛️','atomo atom'],
      ['🉑','aceitavel accept'],
      ['☢️','radioativo radioactive'],
      ['☣️','biohazard'],
      ['📴','celular off mobile off'],
      ['📳','vibracao vibration'],
      ['🈶','tem custo'],
      ['🈚','gratis free'],
      ['🈸','aplicar application'],
      ['🈺','operacao open'],
      ['🈷️','mensal monthly'],
      ['✴️','estrela oito eight star'],
      ['🆚','vs versus'],
      ['💮','flor branca white flower'],
      ['🉐','barganha bargain'],
      ['㊙️','segredo secret'],
      ['㊗️','parabens congratulations'],
      ['🈴','aprovado pass'],
      ['🈵','cheio no vacancy'],
      ['🈹','desconto discount'],
      ['🈲','proibido prohibited'],
      ['🅰️','tipo a a button'],
      ['🅱️','tipo b b button'],
      ['🆎','tipo ab ab button'],
      ['🆑','cl button'],
      ['🅾️','tipo o o button'],
      ['🆘','sos help'],
      ['❌','x errado wrong'],
      ['⭕','o circle'],
      ['🛑','pare stop'],
      ['⛔','proibido no entry'],
      ['📛','crachao name badge'],
      ['🚫','proibido prohibited'],
      ['💯','100 cem perfect'],
      ['💢','irritado anger'],
      ['♨️','onsen hot springs'],
      ['🚷','no pedestrians'],
      ['🚯','no litter'],
      ['🚳','no bicycles'],
      ['🚱','agua nao potavel non potable'],
      ['🔞','dezoito 18 mais'],
      ['📵','no phones'],
      ['🚭','proibido fumar no smoking'],
      ['❗','exclamacao exclamation'],
      ['❕','exclamacao branca'],
      ['❓','interrogacao question'],
      ['❔','interrogacao branca'],
      ['‼️','dois exclamation'],
      ['⁉️','interrogacao exclamation'],
      ['🔅','brilho baixo dim'],
      ['🔆','brilho alto bright'],
      ['〽️','marca part alternation'],
      ['⚠️','aviso warning'],
      ['🚸','crianca children crossing'],
      ['🔱','tridente trident'],
      ['⚜️','flor de lis'],
      ['🔰','iniciante japanese symbol'],
      ['♻️','reciclagem recycle'],
      ['✅','check verde verde green check'],
      ['🈯','reservado reserved'],
      ['💹','grafico iene chart yen'],
      ['❇️','sparkle'],
      ['✳️','asterisco asterisk'],
      ['❎','x errado cross'],
      ['🌐','mundo globe'],
      ['💠','losango diamond'],
      ['Ⓜ️','metro m'],
      ['🌀','ciclone cyclone'],
      ['💤','dormindo zzz'],
      ['🏧','atm caixa eletronico'],
      ['🚾','wc'],
      ['♿','cadeira rodas wheelchair'],
      ['🅿️','estacionamento parking'],
      ['🈳','vago vacancy'],
      ['🈂️','servico service'],
      ['🛂','imigracao passport'],
      ['🛃','alfandega customs'],
      ['🛄','restituicao bagagem baggage'],
      ['🛅','guarda volumes left luggage'],
      ['🚹','homem men'],
      ['🚺','mulher women'],
      ['🚼','bebe baby'],
      ['🚻','banheiro restroom'],
      ['🚮','lixeira trash'],
      ['🎦','cinema'],
      ['📶','sinal signal'],
      ['🈁','aqui here'],
      ['🔣','simbolos input symbols'],
      ['ℹ️','info information'],
      ['🔤','abc letras'],
      ['🔡','minusculas lowercase'],
      ['🔠','maiusculas uppercase'],
      ['🆖','ng'],
      ['🆗','ok'],
      ['🆙','up'],
      ['🆒','cool'],
      ['🆓','free gratis'],
      ['0️⃣','zero'],
      ['1️⃣','um one'],
      ['2️⃣','dois two'],
      ['3️⃣','tres three'],
      ['4️⃣','quatro four'],
      ['5️⃣','cinco five'],
      ['6️⃣','seis six'],
      ['7️⃣','sete seven'],
      ['8️⃣','oito eight'],
      ['9️⃣','nove nine'],
      ['🔟','dez ten'],
      ['🔢','numeros numbers'],
      ['#️⃣','hash'],
      ['*️⃣','asterisco'],
      ['⏏️','eject'],
      ['▶️','play'],
      ['⏸️','pause'],
      ['⏯️','play pause'],
      ['⏹️','stop'],
      ['⏺️','rec record'],
      ['⏭️','proxima next'],
      ['⏮️','anterior previous'],
      ['⏩','avancar fast forward'],
      ['⏪','retroceder rewind'],
      ['⏫','seta cima up'],
      ['⏬','seta baixo down'],
      ['◀️','play reverso'],
      ['🔼','seta cima'],
      ['🔽','seta baixo'],
      ['➡️','seta direita right'],
      ['⬅️','seta esquerda left'],
      ['⬆️','seta cima up'],
      ['⬇️','seta baixo down'],
      ['↗️','noreste northeast'],
      ['↘️','sudeste southeast'],
      ['↙️','sudoeste southwest'],
      ['↖️','noroeste northwest'],
      ['↕️','vertical updown'],
      ['↔️','horizontal leftright'],
      ['↪️','seta direita curva'],
      ['↩️','seta esquerda curva'],
      ['⤴️','seta cima curva'],
      ['⤵️','seta baixo curva'],
      ['🔀','aleatorio shuffle'],
      ['🔁','repetir repeat'],
      ['🔂','repetir uma'],
      ['🔄','girar refresh'],
      ['🔃','girar circular'],
      ['🎵','nota music'],
      ['🎶','notas music'],
      ['➕','mais plus'],
      ['➖','menos minus'],
      ['➗','dividir divide'],
      ['✖️','vezes multiply'],
      ['🟰','igual equal'],
      ['♾️','infinito infinity'],
      ['💲','cifrao dollar'],
      ['💱','cambio exchange'],
      ['™️','trademark'],
      ['©️','copyright'],
      ['®️','registered'],
      ['👁️‍🗨️','olho balao eye speech'],
      ['🔚','fim end'],
      ['🔙','voltar back'],
      ['🔛','on'],
      ['🔝','top'],
      ['🔜','soon'],
      ['〰️','onda wavy'],
      ['➰','laco curly loop'],
      ['➿','laco duplo double curly'],
      ['✔️','check'],
      ['☑️','check box'],
      ['🔘','radio button'],
      ['🔴','vermelho red circle'],
      ['🟠','laranja orange circle'],
      ['🟡','amarelo yellow circle'],
      ['🟢','verde green circle'],
      ['🔵','azul blue circle'],
      ['🟣','roxo purple circle'],
      ['⚫','preto black circle'],
      ['⚪','branco white circle'],
      ['🟤','marrom brown circle'],
      ['🔺','triangulo vermelho red triangle'],
      ['🔻','triangulo baixo red triangle down'],
      ['🔸','laranja diamond small'],
      ['🔹','azul diamond small'],
      ['🔶','laranja diamond large'],
      ['🔷','azul diamond large'],
      ['🔳','quadrado branco button white'],
      ['🔲','quadrado preto button black'],
      ['▪️','quadrado preto small'],
      ['▫️','quadrado branco small'],
      ['◼️','quadrado preto medium'],
      ['◻️','quadrado branco medium'],
      ['◾','quadrado preto'],
      ['◽','quadrado branco'],
      ['⬛','quadrado preto large'],
      ['⬜','quadrado branco large'],
      ['🟥','vermelho square'],
      ['🟧','laranja square'],
      ['🟨','amarelo square'],
      ['🟩','verde square'],
      ['🟦','azul square'],
      ['🟪','roxo square'],
      ['🟫','marrom square'],
    ],
  },
  {
    id: 'flags',
    label: 'Bandeiras',
    icon: '🏳️',
    items: [
      ['🏳️','bandeira branca white flag'],
      ['🏴','bandeira preta black flag'],
      ['🏁','bandeira chegada checkered'],
      ['🚩','bandeira triangular triangular'],
      ['🏳️‍🌈','bandeira lgbt rainbow pride'],
      ['🏳️‍⚧️','bandeira trans transgender'],
      ['🏴‍☠️','bandeira pirata pirate'],
      ['🇧🇷','brasil brazil'],
      ['🇵🇹','portugal'],
      ['🇺🇸','estados unidos usa america'],
      ['🇬🇧','reino unido uk britain'],
      ['🇨🇦','canada'],
      ['🇲🇽','mexico'],
      ['🇦🇷','argentina'],
      ['🇨🇱','chile'],
      ['🇨🇴','colombia'],
      ['🇵🇪','peru'],
      ['🇺🇾','uruguai uruguay'],
      ['🇵🇾','paraguai paraguay'],
      ['🇧🇴','bolivia'],
      ['🇻🇪','venezuela'],
      ['🇪🇨','equador ecuador'],
      ['🇪🇸','espanha spain'],
      ['🇫🇷','franca france'],
      ['🇩🇪','alemanha germany'],
      ['🇮🇹','italia italy'],
      ['🇯🇵','japao japan'],
      ['🇰🇷','coreia korea south'],
      ['🇨🇳','china'],
      ['🇮🇳','india'],
      ['🇷🇺','russia'],
      ['🇦🇺','australia'],
      ['🇳🇿','nova zelandia new zealand'],
      ['🇿🇦','africa do sul south africa'],
      ['🇪🇬','egito egypt'],
      ['🇳🇬','nigeria'],
      ['🇸🇦','arabia saudita saudi'],
      ['🇦🇪','emirados uae'],
      ['🇮🇱','israel'],
      ['🇹🇷','turquia turkey'],
      ['🇬🇷','grecia greece'],
      ['🇳🇱','holanda netherlands'],
      ['🇧🇪','belgica belgium'],
      ['🇨🇭','suica switzerland'],
      ['🇦🇹','austria'],
      ['🇸🇪','suecia sweden'],
      ['🇳🇴','noruega norway'],
      ['🇩🇰','dinamarca denmark'],
      ['🇫🇮','finlandia finland'],
      ['🇮🇪','irlanda ireland'],
      ['🇵🇱','polonia poland'],
      ['🇨🇿','tchequia czech'],
      ['🇭🇺','hungria hungary'],
      ['🇷🇴','romenia romania'],
      ['🇺🇦','ucrania ukraine'],
      ['🇹🇭','tailandia thailand'],
      ['🇻🇳','vietnam'],
      ['🇮🇩','indonesia'],
      ['🇵🇭','filipinas philippines'],
      ['🇲🇾','malasia malaysia'],
      ['🇸🇬','singapura singapore'],
      ['🇭🇰','hong kong'],
      ['🇹🇼','taiwan'],
      ['🇨🇺','cuba'],
      ['🇩🇴','republica dominicana'],
      ['🇵🇷','porto rico puerto rico'],
      ['🇯🇲','jamaica'],
      ['🇲🇦','marrocos morocco'],
      ['🇰🇪','quenia kenya'],
      ['🇪🇺','uniao europeia european union'],
      ['🇺🇳','onu united nations'],
    ],
  },
];
