// Posts de exemplo — alunos de intercâmbio em diferentes países.
// Servem como "seed" do Feed News pra deixar a comunidade viva enquanto
// usuários reais não publicam. Não são gravados no banco — só exibidos.

export interface SampleFeedPost {
  id: string;
  username: string;
  fotoPerfil?: string;
  text: string;
  image?: string;
  createdAt: string;
  likes: string[];
  views: string[];
  comments: never[];
  __sample?: true; // flag pra a UI tratar como read-only
}

// Avatares variados (Unsplash people)
const AV = (seed: string) =>
  `https://images.unsplash.com/photo-${seed}?w=160&h=160&fit=crop&crop=faces`;

const IMG = (seed: string) =>
  `https://images.unsplash.com/photo-${seed}?w=900&h=600&fit=crop`;

// Distribui os timestamps em diferentes intervalos pra parecer orgânico
const t = (hoursAgo: number) =>
  new Date(Date.now() - hoursAgo * 3600 * 1000).toISOString();

export const SAMPLE_POSTS: SampleFeedPost[] = [
  {
    id: 'sample-1',
    username: 'mariana_dublin',
    fotoPerfil: AV('1494790108377-be9c29b29330'),
    text: 'Cheguei em Dublin há 3 semanas e ainda tô me acostumando com o clima! 🌧️ Mas a galera é super receptiva. Já achei trabalho de barista no centro, paga 13€/h. Vale demais a pena pra quem tá começando. Qualquer dúvida sobre PPS Number, me chama no privado!',
    image: IMG('1486325212027-8081e485255e'),
    createdAt: t(2),
    likes: ['pedro_galway', 'ana_cork', 'lucas_dublin22'],
    views: [],
    comments: [],
    __sample: true,
  },
  {
    id: 'sample-2',
    username: 'rafael_london',
    fotoPerfil: AV('1500648767791-00dcc994a43e'),
    text: 'Primeira semana em Londres concluída! O metrô (Tube) é caro mas SUPER eficiente. Dica de ouro: comprem a Oyster Card no primeiro dia. Tô estudando inglês na escola EC London e curtindo demais o intercâmbio. 🇬🇧',
    createdAt: t(5),
    likes: ['fabi_uk', 'gustavo_brixton'],
    views: [],
    comments: [],
    __sample: true,
  },
  {
    id: 'sample-3',
    username: 'beatriz_toronto',
    fotoPerfil: AV('1438761681033-6461ffad8d80'),
    text: 'Toronto na primavera é outra coisa! 🌸 Saí de Curitiba há 2 meses e nunca achei que ia me adaptar tão rápido. Estudo de manhã na ILSC e trabalho à tarde num café da Queen Street. Salário mínimo aqui é CAD 17,20 — dá pra viver bem dividindo apto.',
    image: IMG('1517090504586-fde19ea6066f'),
    createdAt: t(8),
    likes: ['julia_canada', 'matheus_van'],
    views: [],
    comments: [],
    __sample: true,
  },
  {
    id: 'sample-4',
    username: 'lucas_sydney',
    fotoPerfil: AV('1507003211169-0a1dd7228f2d'),
    text: 'Sydney é PARAÍSO 🏝️ Manhã na praia de Bondi, aula de tarde, trabalho no restaurante à noite. O visto Student Australia permite 48h/quinzena de trabalho. Já economizei pra viajar pra Melbourne semana que vem!',
    image: IMG('1506973035872-a4ec16b8e8d9'),
    createdAt: t(12),
    likes: ['camila_aus', 'pedro_melb', 'rodrigo_qld'],
    views: [],
    comments: [],
    __sample: true,
  },
  {
    id: 'sample-5',
    username: 'julia_lisbon',
    fotoPerfil: AV('1531123897727-8f129e1688ce'),
    text: 'Lisboa é incrível pra brasileiro 🇵🇹 Sem barreira de idioma (mais ou menos kkk), comida boa, transporte público bom. Estou na Universidade Nova fazendo mestrado. O custo de vida é bem mais alto que parece — aluguel virou cilada nos últimos 2 anos. Preparem o bolso!',
    createdAt: t(14),
    likes: ['marcos_porto', 'sofia_lisboa'],
    views: [],
    comments: [],
    __sample: true,
  },
  {
    id: 'sample-6',
    username: 'pedro_berlin',
    fotoPerfil: AV('1472099645785-5658abf4ff4e'),
    text: 'Berlim 🇩🇪 é uma das cidades mais multiculturais que já vi. Faço Ausbildung (formação técnica dual) em logística — recebo 1.200€/mês como estudante. Alemão é DURO mas vale a pena. Conselho: façam B1 antes de chegar, faz toda a diferença.',
    image: IMG('1528728329032-2972f65dfb3f'),
    createdAt: t(20),
    likes: ['lara_munique', 'henrique_de'],
    views: [],
    comments: [],
    __sample: true,
  },
  {
    id: 'sample-7',
    username: 'camila_barcelona',
    fotoPerfil: AV('1488426862026-3ee34a7d66df'),
    text: 'Barcelona tem o ritmo perfeito 🇪🇸 Estudo na UB de manhã, à tarde curto a cidade. Comida boa, gente acolhedora, praia perto. O NIE pra estudante demora pra sair mas vale a paciência. Tô fazendo mestrado em design e amando!',
    createdAt: t(26),
    likes: ['rafa_madrid', 'andre_bcn', 'patricia_es'],
    views: [],
    comments: [],
    __sample: true,
  },
  {
    id: 'sample-8',
    username: 'gabriel_dublin',
    fotoPerfil: AV('1463453091185-61582044d556'),
    text: 'Dica de quem já mora há 1 ano em Dublin: NÃO aluga em Dublin 4 ou 6 logo de cara. Procura nos arredores tipo Drumcondra, Phibsborough, Stoneybatter. Aluguel cai pela metade e tem ônibus 24h pro centro. Bons estudos pra galera nova! ☘️',
    createdAt: t(30),
    likes: ['mariana_dublin', 'thiago_ire'],
    views: [],
    comments: [],
    __sample: true,
  },
  {
    id: 'sample-9',
    username: 'fernanda_vancouver',
    fotoPerfil: AV('1573497019940-1c28c88b4f3e'),
    text: 'Vancouver é uma cidade que respira natureza 🏔️ A 30min do centro você tá no Stanley Park ou em Grouse Mountain. Inverno gelado mas suportável. Tô fazendo college em Marketing — depois consigo PGWP (visto de trabalho pós-graduação) por 3 anos!',
    image: IMG('1559511260-66a654ae982a'),
    createdAt: t(36),
    likes: ['mariana_van', 'leo_canada'],
    views: [],
    comments: [],
    __sample: true,
  },
  {
    id: 'sample-10',
    username: 'thiago_melbourne',
    fotoPerfil: AV('1492562080023-ab3db95bfbce'),
    text: 'Melbourne ganhou meu coração ❤️ Cidade mais artística que Sydney, café de outro mundo, vida noturna bombando. Faço English course na Kaplan e trabalho de delivery. Australianos são MUITO de boa, dá pra ser amigo deles fácil.',
    createdAt: t(42),
    likes: ['lucas_sydney', 'bia_aus'],
    views: [],
    comments: [],
    __sample: true,
  },
  {
    id: 'sample-11',
    username: 'isabela_madrid',
    fotoPerfil: AV('1502685104226-ee32379fefbe'),
    text: 'Madrid 🇪🇸 é vida! Tapas, vinho, Retiro, Prado, sol o ano todo. Faço Erasmus pela USP na Universidad Complutense. Já viajei pra Sevilha, Toledo e Granada. Conselho: aprendam castelhano de verdade antes — é diferente do que a gente acha que sabe!',
    image: IMG('1543783207-ec64e4d95325'),
    createdAt: t(50),
    likes: ['camila_barcelona', 'rafa_madrid', 'pedro_es'],
    views: [],
    comments: [],
    __sample: true,
  },
  {
    id: 'sample-12',
    username: 'rodrigo_porto',
    fotoPerfil: AV('1506794778202-cad84cf45f1d'),
    text: 'Porto 🇵🇹 menos turística que Lisboa, mais real. Pessoas autênticas, comida fenomenal (francesinha 🤤) e custo de vida ainda razoável. Universidade do Porto é top. Recomendo MUITO pra quem quer estudar em Portugal sem o caos lisboeta.',
    createdAt: t(58),
    likes: ['julia_lisbon', 'marcos_porto'],
    views: [],
    comments: [],
    __sample: true,
  },
  {
    id: 'sample-13',
    username: 'patricia_munich',
    fotoPerfil: AV('1534528741775-53994a69daeb'),
    text: 'Munique no verão é mágica ✨ Cerveja artesanal, parques enormes, festivais... e no inverno os Alpes a 1h de trem. Pago 850€ de aluguel num studio. Estou na TUM cursando engenharia. Bayern é cara mas top demais!',
    image: IMG('1547036967-23d11aacaee0'),
    createdAt: t(70),
    likes: ['pedro_berlin', 'henrique_de'],
    views: [],
    comments: [],
    __sample: true,
  },
  {
    id: 'sample-14',
    username: 'andre_cork',
    fotoPerfil: AV('1542909168-82c3e7fdca5c'),
    text: 'Cork, Irlanda 🍀 — pequena, charmosa, mais barata que Dublin e com excelentes escolas. Tô na Cork English College, gastando metade do que gastaria em Dublin. Galera é mais calma e tem um pub histórico em cada esquina. Adoro!',
    createdAt: t(82),
    likes: ['gabriel_dublin', 'mariana_dublin'],
    views: [],
    comments: [],
    __sample: true,
  },
  {
    id: 'sample-15',
    username: 'leticia_montreal',
    fotoPerfil: AV('1521252659862-eec69941b071'),
    text: 'Montreal 🇨🇦 — bilíngue francês/inglês, vibe europeia na América do Norte. Tô aprendendo francês na UdeM. Inverno é brutal (-25°C) mas o resto do ano é incrível. Quebec dá bolsas pra estudantes internacionais, vale pesquisar!',
    image: IMG('1519178614-68673b201f36'),
    createdAt: t(90),
    likes: ['fernanda_vancouver', 'beatriz_toronto'],
    views: [],
    comments: [],
    __sample: true,
  },
  {
    id: 'sample-16',
    username: 'felipe_galway',
    fotoPerfil: AV('1503443207922-dff7d543fd0e'),
    text: 'Galway 🇮🇪 é o segredo melhor guardado da Irlanda. Cidade universitária, vida noturna animada, paisagens INSANAS no Connemara a 30min. Faço General English na GCD e trabalho de garçom. Aluguel mais em conta que Dublin, comunidade brasileira pequena mas unida ☘️',
    createdAt: t(102),
    likes: ['andre_cork', 'gabriel_dublin'],
    views: [],
    comments: [],
    __sample: true,
  },
  {
    id: 'sample-17',
    username: 'bruna_auckland',
    fotoPerfil: AV('1517841905240-472988babdf9'),
    text: 'Nova Zelândia 🇳🇿 é OUTRO planeta. Auckland é multicultural e segura. Tô fazendo Working Holiday — visto que permite trabalhar 1 ano. Salário mínimo aqui é NZD 23/h. Já economizei pra dar a volta nas duas ilhas. Recomendo MUITO!',
    image: IMG('1507699622108-4be3abd695ad'),
    createdAt: t(118),
    likes: ['lucas_sydney', 'thiago_melbourne'],
    views: [],
    comments: [],
    __sample: true,
  },
  {
    id: 'sample-18',
    username: 'henrique_frankfurt',
    fotoPerfil: AV('1500648767791-00dcc994a43e'),
    text: 'Frankfurt 🇩🇪 — não é a Alemanha mais bonita, mas é a mais conectada. Aeroporto é um hub mundial, tô viajando pra um país europeu diferente a cada mês de baixo custo. Mestrado em finanças na Goethe Uni. Cidade pequena, ótima qualidade de vida!',
    createdAt: t(134),
    likes: ['patricia_munich', 'pedro_berlin'],
    views: [],
    comments: [],
    __sample: true,
  },
  {
    id: 'sample-19',
    username: 'sofia_valencia',
    fotoPerfil: AV('1487412720507-e7ab37603c6f'),
    text: 'Valencia 🇪🇸 — sol, praia, paella original 🥘, custo de vida AMIGO. Estudo na Universitat de València. Aluguel num quarto compartilhado: 350€. Cidade tem vibe espanhola autêntica sem o turismo doido de Barcelona. Recomendo pra quem busca calmaria.',
    image: IMG('1543783207-ec64e4d95325'),
    createdAt: t(150),
    likes: ['isabela_madrid', 'camila_barcelona'],
    views: [],
    comments: [],
    __sample: true,
  },
  {
    id: 'sample-20',
    username: 'matheus_edinburgh',
    fotoPerfil: AV('1500648767791-2c1c41bcfa00'),
    text: 'Edimburgo, Escócia 🏴󠁧󠁢󠁳󠁣󠁴󠁿 — castelo medieval no meio da cidade, ar puro, sotaque escocês que demora pra entender 😅. Faço PhD na University of Edinburgh. Bolsa cobre tudo. Whisky, gaita de fole e arquitetura gótica viraram minha rotina. Slainte! 🥃',
    createdAt: t(168),
    likes: ['rafael_london', 'fabi_uk'],
    views: [],
    comments: [],
    __sample: true,
  },
];
